# The key name we will use
$comment = "Generated by Azure"
$priKeyName = "stweukeytslg001"
$pubKeyName = $priKeyName + ".pub"
# Remove any existing keys in order to produce new ones
try {
    Remove-Item $priKeyName
    Remove-Item $pubKeyName     
} catch {
    ""
}

# Create the path for the keys
New-Item -Path . -Name $priKeyName -ItemType "file"
# Get the path
$fname=(Get-ChildItem -Path $keyName).FullName
Remove-Item $fname
ssh-keygen -b 4096 -C $comment -f $fname -m PEM -t rsa