# The key name we will use
$rg="rg-st-weu-slg-t"
$subId="8ef27501-4e51-4676-9988-5bf63a6b9dc1"
$comment = "Generated by Azure"
$priKeyName = "stweukeytslg001"
$pubKeyName = $priKeyName + ".pub"
# Remove any existing keys in order to produce new ones
try {
    Remove-Item $priKeyName
    Remove-Item $pubKeyName     
} catch {
    ""
}

# Create the path for the keys
New-Item -Path . -Name $priKeyName -ItemType "file"
# Get the path
$fname=(Get-ChildItem -Path $priKeyName).FullName
Remove-Item $fname
ssh-keygen -b 4096 -C $comment -f $fname -m PEM -t rsa
$rsa=Get-Content $pubKeyName
$template=Get-Content .\template.json
$templateToDeploy = $template.replace('"properties": {}',"properties"+":{ ""publicKey"":"""+$rsa+"""}")
Set-Content -Path '.\templateToDeploy.json' -Value $templateToDeploy
$deploymentFile=(Get-ChildItem -Path '.\templateToDeploy.json').FullName
$parameterFile=(Get-ChildItem -Path '.\parameters.json' ).FullName
Connect-AzAccount
Set-AzContext $subId
New-AzResourceGroupDeployment -Name $priKeyName -ResourceGroupName $rg -TemplateFile $deploymentFile -TemplateParameterFile $parameterFile